apiVersion: v1
kind: PersistentVolume
metadata:
  name: go-carbon-pv
  namespace: carbon-cluster
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/go-carbon