apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-carbon-pvc
  namespace: carbon-cluster
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: manual
