apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: go-carbon
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-carbon
  serviceName: go-carbon-headless
  template:
    metadata:
      labels:
        app: go-carbon
    spec:
      containers:
      - name: go-carbon
        image: mnadeempml/carbon:latest
        ports:
        - containerPort: 2003
          name: tcp-metrics
          protocol: TCP
        - containerPort: 2003
          name: udp-metrics
          protocol: UDP
        - containerPort: 8080
          name: internal
          protocol: TCP
        volumeMounts:
        - name: config-volume
          mountPath: /etc/go-carbon
        - name: data-volume
          mountPath: /data/go-carbon
      volumes:
      - name: config-volume
        configMap:
          name: go-carbon-config
      - name: data-volume
        persistentVolumeClaim:
          claimName: go-carbon-pvc
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: go-carbon-headless
#  namespace: carbon
#spec:
#  clusterIP: None
#  selector:
#    app: go-carbon
