---
apiVersion: v1
kind: ConfigMap
metadata:
  name: go-carbon-config
  namespace: default
data:
  go-carbon.conf: |
    [common]
    user = "root"
    graph-prefix = "carbon.agents.{host}"
    metric-endpoint = "local"
    metric-interval = "1m0s"
    max-cpu = 1
    [whisper]
    data-dir = "/var/lib/graphite/whisper"
    schemas-file = "/etc/go-carbon/storage-schemas.conf"
    aggregation-file = "/etc/go-carbon/storage-aggregation.conf"
    workers = 2
    max-updates-per-second = 0
    sparse-create = false
    flock = true
    enabled = true
    hash-filenames = true
    remove-empty-file = true
    [cache]
    max-size = 1000000
    write-strategy = "max"
    bloom-size = 0
    [udp]
    listen = ":2003"
    enabled = true
    buffer-size = 0
    [tcp]
    listen = ":2003"
    enabled = true
    buffer-size = 0
    [pickle]
    listen = ":2004"
    max-message-size = 67108864
    enabled = true
    buffer-size = 0
    [carbonlink]
    listen = "127.0.0.1:7002"
    enabled = true
    read-timeout = "30s"
    [grpc]
    listen = "127.0.0.1:7003"
    enabled = true
    [tags]
    enabled = false
    tagdb-url = "http://127.0.0.1:8000"
    tagdb-chunk-size = 32
    tagdb-update-interval = 100
    local-dir = "/var/lib/graphite/11212tagging/"
    tagdb-timeout = "1s"
    [carbonserver]
    listen = "0.0.0.0:8080"
    enabled = true
    buckets = 10
    max-creates-per-second = 0
    metrics-as-counters = false
    read-timeout = "60s"
    write-timeout = "60s"
    request-timeout = "60s"
    query-cache-enabled = true
    streaming-query-cache-enabled = false
    query-cache-size-mb = 0
    find-cache-enabled = true
    find-cache-size-mb = 0
    glob-cache-enabled = true
    glob-cache-size-mb = 0
    trigram-index = true
    scan-frequency = "5m0s"
    trie-index = false
    concurrent-index = false
    realtime-index = 0
    max-inflight-requests = 0
    no-service-when-index-is-not-ready = false
    cache-scan = false
    max-globs = 100
    fail-on-max-globs = false
    max-metrics-globbed  = 30000
    max-metrics-rendered = 1000
    max-fetch-data-goroutines = 0
    graphite-web-10-strict-mode = true
    empty-result-ok = false
    do-not-log-404s = false
    internal-stats-dir = ""
    stats-percentiles = [99, 98, 95, 75, 50]
    #[prometheus]
    #enabled = true
    [[logging]]
    logger = ""
    file = "stdout"
    # Log level: "debug", "info", "warn", "error", "dpanic", "panic", and "fatal"
    level = "info"
    encoding = "json"
    encoding-time = "iso8601"
    encoding-duration = "seconds"
  storage-schemas.conf: |
    [default]
    pattern = .*
    retentions = 60s:30d,1h:5y
    compressed = false
  storage-aggregation.conf: |
    [default]
    pattern = .*
    xFilesFactor = 0.5
    aggregationMethod = average
