---
apiVersion: v1
kind: Service
metadata:
  name: carbon-server
  namespace: default
spec:
  clusterIP: None
  selector:
    app: go-carbon
  ports:
  - port: 8080
    name: internal
    protocol: TCP
    targetPort: internal
---
apiVersion: v1
kind: Service
metadata:
  name: carbon-metrics
  namespace: default
spec:
  type: NodePort
  selector:
    app: go-carbon
  ports:
  - port: 2003
    name: tcp-metrics
    targetPort: tcp-metrics
    protocol: TCP
  - port: 2003
    name: udp-metrics
    targetPort: udp-metrics
    protocol: UDP
